---

extends: default

rules:
  braces:
    level: warning
    max-spaces-inside: 1
  brackets:
    level: warning
    max-spaces-inside: 1
  colons:
    level: warning
  commas: disable
  comments: disable
  comments-indentation: disable
  document-start: disable
  empty-lines:
    max: 2
    max-start: 1
    max-end: 1
    level: warning
  hyphens:
    level: warning
  indentation:
    level: warning
    indent-sequences: consistent
  line-length:
    max: 300
    level: warning
    allow-non-breakable-inline-mappings: true
  truthy: disable
  trailing-spaces: disable